# Generated by Django 5.2.7 on 2025-11-07 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Conferenceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('Session_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('session_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(help_text='Nom de la salle (lettres et chiffres seulement)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom de la salle ne peut contenir que des lettres, chiffres et espaces.', regex='^[a-zA-Z0-9\\s]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Conferenceapp.conference')),
            ],
        ),
    ]
